config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'
  resources :artists
  resources :albums do
    resources :songs
  end

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id           :integer          not null, primary key
#  name         :string
#  release_date :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  artist_id    :integer
#

class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :songs, dependent: :destroy
  validates_presence_of :name
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  validates_presence_of :name

end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id           :integer          not null, primary key
#  name         :string
#  track_number :integer
#  album_id     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Song < ActiveRecord::Base
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :release_date, :artist_name, :artist_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :image_url)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_album
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params.merge(album_id: @album.id))

    respond_to do |format|
      if @song.save
        format.html { redirect_to album_song_url(@album, @song), notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to album_song_url(@album, @song), notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to album_songs_url(@album), notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_album
      @album = Album.find(params[:album_id])
    end

    def set_song
      @song = @album.songs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :track_number, :album_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_album.html.erb
<!-- one album -->
<div class="row album">

  <div class="panel panel-default">
    <div class="panel-body">


    <!-- begin album internal row -->
      <div class='row'>
        <div class="col-md-3 col-xs-12 thumbnail album-art">
          <%= image_tag '800x800.png', alt: 'album image' %>
        </div>

        <div class="col-md-9 col-xs-12">
          <ul class="list-group">
            <li class="list-group-item">
              <h4 class='inline-header'>Album Name:</h4>
              <span class='album-name'><%= link_to album.name, album %></span>
            </li>

            <li class="list-group-item">
              <h4 class='inline-header'>Artist Name:</h4>
              <span class='artist-name'><%= link_to album.artist.name, artist_path(album.artist) %></span>
            </li>

            <li class="list-group-item">
              <h4 class='inline-header'>Released date:</h4>
              <span class='album-releaseDate'><%= album.release_date %></span>
            </li>

          </ul>
        </div>

      </div>
      <!-- end of album internal row -->

      <div class='panel-footer'>
        <div class='panel-footer'>
          <%= link_to 'Add Song', new_album_song_path(album), class: 'btn btn-primary' %>
          <%= link_to 'Album Details', album, class: 'btn btn-primary' %>
          <%= link_to 'Delete Album', album, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete '#{album.name}'?" } %>
          <%= link_to 'Edit Album', edit_album_path(album), class: 'btn btn-info' %>
          <%= link_to 'View Songs', album_songs_path(album), class: 'btn btn-info' %>
        </div>

      </div>

    </div>
  </div>
</div>
<!-- end one album -->

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :release_date %>
    <%= f.input :artist_id, :collection => Artist.all, label_method: :name, value_method: :id, include_blank: false %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Album', new_album_path, class: 'btn btn-primary' %>
<%= link_to 'View Artists', artists_path, class: 'btn btn-primary' %>

<h1>Albums</h1>
  <%= render @albums, collection: @albums %>
<br>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @album.release_date %>
</p>

<p>
  <strong>Artist name:</strong>
  <%= link_to @album.artist.name, artist_path(@album.artist) %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/artists/_artist.html.erb
<!-- one artist -->
<div class="row artist">

  <div class="panel panel-default">
    <div class="panel-body">


    <!-- begin artist internal row -->
      <div class='row'>
        <div class="col-md-4 col-xs-12 thumbnail artist-art">
          <% if artist.image_url %>
            <img src="<%=artist.image_url%>" alt='artist image'>
          <% else %>
            <%= image_tag '800x800.png', alt: 'artist image' %>
          <% end %>
        </div>

        <div class="col-md-8 col-xs-12">
          <ul class="list-group">
            <li class="list-group-item">
              <h4 class='inline-header'>Artist Name:</h4>
              <span class='artist-name'><%= artist.name %></span>
            </li>

            <li class="list-group-item">
              <h4 class='inline-header'>Albums:</h4>
              <ul>
                <% artist.albums.each do |album| %>
                  <li> <%= link_to album.name, album %> - (<%= album.release_date.year %>)</li>
                <% end %>
              </ul>
            </li>

          </ul>
        </div>

      </div>
      <!-- end of artist internal row -->

      <div class='panel-footer'>
        <div class='panel-footer'>
          <%= link_to 'Delete Artist', artist, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete '#{artist.name}'?" } %>
          <%= link_to 'Edit Artist', edit_artist_path(artist), class: 'btn btn-info' %>

        </div>

      </div>

    </div>
  </div>
</div>
<!-- end one artist -->

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Artist', new_artist_path, class: 'btn btn-primary' %>
<%= link_to 'View Albums', albums_path, class: 'btn btn-primary' %>


<h1>Listing Artists</h1>

<%= render @artists, collection: @artists %>
<br>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @artist.image_url %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TunelyRed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="jumbotron">
    <div class="container">
      <h1>Welcome to tunely</h1>
      <p>Your music binder!</p>
    </div>
  </div>

  <div class='container'><div class='row'>
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      <%= yield %>
    </div>
  </div></div>
</body>
</html>

app/views/songs/_form.html.erb
<%= simple_form_for([@album, @song]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :track_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', album_song_path(@album, @song) %> |
<%= link_to 'Back', album_songs_path(@album) %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Track number</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.track_number %></td>
        <td><%= song.album.name %></td>
        <td><%= link_to 'Show', album_song_path(@album, song) %></td>
        <td><%= link_to 'Edit', edit_album_song_path(@album, song) %></td>
        <td><%= link_to 'Destroy', album_song_path(@album, song), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_album_song_path(1) %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', album_songs_path(@album) %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Track number:</strong>
  <%= @song.track_number %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album.name %> - <%= @song.album.artist.name %>
</p>

<%= link_to 'Edit', edit_album_song_path(@album, @song) %> |
<%= link_to 'Back', album_songs_path(@album) %>